package main

const PRIVATE_KEY = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBHnH3MqUja9ILIQzEYZmykIXxXP/wiXvp1Zl9c5vJApQAAAIgB7NwuAezc
LgAAAAtzc2gtZWQyNTUxOQAAACBHnH3MqUja9ILIQzEYZmykIXxXP/wiXvp1Zl9c5vJApQ
AAAEBJ1GldAXX9344ybdWRxcSZ/O0y8jcGg5KVo4maLOrbBUecfcypSNr0gshDMRhmbKQh
fFc//CJe+nVmX1zm8kClAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----`
